In [1]:
!pip install wandb==0.16.3
!pip install ydata-profiling==4.13.0
!pip install pandas==2.2.0

Collecting wandb==0.16.3
  Downloading wandb-0.16.3-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: Click!=8.0.0,>=7.1 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from wandb==0.16.3) (8.3.0)
Requirement already satisfied: GitPython!=3.1.29,>=1.0.0 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from wandb==0.16.3) (3.1.45)
Requirement already satisfied: requests<3,>=2.0.0 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from wandb==0.16.3) (2.32.5)
Requirement already satisfied: psutil>=5.0.0 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from wandb==0.16.3) (7.1.1)
Requirement already satisfied: sentry-sdk>=1.0.0 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from wandb==0.16.3) (2.42.1)
Collecting docker-pycreds>=0.4.0 (from wandb==0.16.3)
  Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: PyYAML in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from wandb==0.16.3) (6.0.3)
Collecting setproctitle (from wandb==0.16.3)
  Using cached setproctitle-1.3.7-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (10 kB)
Requirement already satisfied: setuptools in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from wandb==0.16.3) (80.9.0)
Collecting appdirs>=1.4.3 (from wandb==0.16.3)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting protobuf!=4.21.0,<5,>=3.19.0 (from wandb==0.16.3)
  Using cached protobuf-4.25.8-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Requirement already satisfied: six>=1.4.0 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from docker-pycreds>=0.4.0->wandb==0.16.3) (1.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from GitPython!=3.1.29,>=1.0.0->wandb==0.16.3) (4.0.12)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from requests<3,>=2.0.0->wandb==0.16.3) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from requests<3,>=2.0.0->wandb==0.16.3) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from requests<3,>=2.0.0->wandb==0.16.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from requests<3,>=2.0.0->wandb==0.16.3) (2025.10.5)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from gitdb<5,>=4.0.1->GitPython!=3.1.29,>=1.0.0->wandb==0.16.3) (5.0.2)
Downloading wandb-0.16.3-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 23.3 MB/s eta 0:00:00
Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Using cached protobuf-4.25.8-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
Using cached setproctitle-1.3.7-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (33 kB)
Installing collected packages: appdirs, setproctitle, protobuf, docker-pycreds, wandb
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.33.0
    Uninstalling protobuf-6.33.0:
      Successfully uninstalled protobuf-6.33.0
  Attempting uninstall: wandb
    Found existing installation: wandb 0.22.0
    Uninstalling wandb-0.22.0:
      Successfully uninstalled wandb-0.22.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-proto 1.38.0 requires protobuf<7.0,>=5.0, but you have protobuf 4.25.8 which is incompatible.
Successfully installed appdirs-1.4.4 docker-pycreds-0.4.0 protobuf-4.25.8 setproctitle-1.3.7 wandb-0.16.3
ERROR: Ignored the following versions that require a different python version: 4.0.0 Requires-Python >=3.7, <3.11; 4.1.0 Requires-Python >=3.7, <3.12; 4.1.1 Requires-Python >=3.7, <3.12; 4.1.2 Requires-Python >=3.7, <3.12; 4.10.0 Requires-Python <3.13,>=3.7; 4.11.0 Requires-Python <3.13,>=3.7; 4.12.0 Requires-Python <3.13,>=3.7; 4.12.1 Requires-Python <3.13,>=3.7; 4.12.2 Requires-Python <3.13,>=3.7; 4.13.0 Requires-Python <3.13,>=3.7; 4.14.0 Requires-Python <3.13,>=3.7; 4.15.0 Requires-Python <3.13,>=3.7; 4.15.1 Requires-Python <3.13,>=3.7; 4.16.0 Requires-Python <3.13,>=3.7; 4.16.1 Requires-Python <3.13,>=3.7; 4.2.0 Requires-Python >=3.7, <3.12; 4.3.0 Requires-Python >=3.7, <3.12; 4.3.1 Requires-Python >=3.7, <3.12; 4.3.2 Requires-Python >=3.7, <3.12; 4.4.0 Requires-Python >=3.7, <3.12; 4.5.0 Requires-Python >=3.7, <3.12; 4.5.1 Requires-Python >=3.7, <3.12; 4.6.0 Requires-Python >=3.7, <3.12; 4.6.1 Requires-Python >=3.7, <3.12; 4.6.2 Requires-Python >=3.7, <3.12; 4.6.3 Requires-Python >=3.7, <3.12; 4.6.4 Requires-Python >=3.7, <3.12; 4.6.5 Requires-Python >=3.7, <3.12; 4.7.0 Requires-Python >=3.7, <3.13; 4.8.3 Requires-Python <3.13,>=3.7; 4.9.0 Requires-Python <3.13,>=3.7
ERROR: Could not find a version that satisfies the requirement ydata-profiling==4.13.0 (from versions: 4.17.0)
ERROR: No matching distribution found for ydata-profiling==4.13.0
Collecting pandas==2.2.0
  Downloading pandas-2.2.0.tar.gz (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 39.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy<2,>=1.26.0 (from pandas==2.2.0)
  Using cached numpy-1.26.4-cp313-cp313-linux_x86_64.whl
Requirement already satisfied: python-dateutil>=2.8.2 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from pandas==2.2.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from pandas==2.2.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from pandas==2.2.0) (2025.2)
Requirement already satisfied: six>=1.5 in /home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas==2.2.0) (1.17.0)
Building wheels for collected packages: pandas
  Building wheel for pandas (pyproject.toml) ... done
  Created wheel for pandas: filename=pandas-2.2.0-cp313-cp313-linux_x86_64.whl size=45741675 sha256=e58ade86bd244d37441c188a18881d446848054bf14d0d2e0d9f1c4e7d9a96dc
  Stored in directory: /home/dtay_dev/.cache/pip/wheels/a2/91/62/050ca8ba28830362e52f9365f82dcd1db14fc6e52caabe9abb
Successfully built pandas
Installing collected packages: numpy, pandas
  Attempting uninstall: numpy
    Found existing installation: numpy 2.3.3
    Uninstalling numpy-2.3.3:
      Successfully uninstalled numpy-2.3.3
  Attempting uninstall: pandas
    Found existing installation: pandas 2.3.2
    Uninstalling pandas-2.3.2:
      Successfully uninstalled pandas-2.3.2
Successfully installed numpy-1.26.4 pandas-2.2.0

1. Fetch the artifact we just created (sample.csv) from W&B and read it with pandas:

In [2]:
import wandb
import pandas as pd
# Note that we use save_code=True in the call to wandb.init so the notebook is uploaded and versioned by W&B
run = wandb.init(project="nyc_airbnb", group="eda", save_code=True)
local_path = wandb.use_artifact("sample.csv:latest").file()
df = pd.read_csv(local_path)

/home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages/wandb/sdk/launch/builder/build.py:11: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/home/dtay_dev/miniconda3/envs/nyc_airbnb_dev/lib/python3.13/site-packages/wandb/sdk/launch/builder/build.py:11: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
wandb: Currently logged in as: dallas-taylor96 (dallas-taylor96-western-governors-university). Use `wandb login --relogin` to force relogin
wandb: WARNING Unable to render HTML, can't import display from ipython.core
wandb: WARNING Unable to render HTML, can't import display from ipython.core
wandb: WARNING Unable to render HTML, can't import display from ipython.core
wandb: WARNING Unable to render HTML, can't import display from ipython.core
wandb: WARNING Unable to render HTML, can't import display from ipython.core
wandb: WARNING Unable to render HTML, can't import display from ipython.core

2. Explore the data in df

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20000 non-null  int64
 1   name                            19993 non-null  object
 2   host_id                         20000 non-null  int64
 3   host_name                       19992 non-null  object
 4   neighbourhood_group             20000 non-null  object
 5   neighbourhood                   20000 non-null  object
 6   latitude                        20000 non-null  float64
 7   longitude                       20000 non-null  float64
 8   room_type                       20000 non-null  object
 9   price                           20000 non-null  int64
 10  minimum_nights                  20000 non-null  int64
 11  number_of_reviews               20000 non-null  int64
 12  last_review                     15877 non-null  object
 13  reviews_per_month               15877 non-null  float64
 14  calculated_host_listings_count  20000 non-null  int64
 15  availability_365                20000 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 2.4+ MB

In [4]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,2.000000e+04,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,15877.000000,20000.000000,20000.000000
mean,1.892380e+07,6.746034e+07,40.728455,-73.952125,153.269050,6.992100,23.274100,1.377446,6.955450,112.901200
std,1.101223e+07,7.857936e+07,0.054755,0.046559,243.325609,21.645449,44.927793,1.683006,32.433831,131.762226
min,2.539000e+03,2.571000e+03,40.508730,-74.239140,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.393540e+06,7.853718e+06,40.689420,-73.983030,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.952117e+07,3.111431e+07,40.722730,-73.955640,105.000000,2.000000,5.000000,0.720000,1.000000,44.000000
75%,2.912936e+07,1.068426e+08,40.762990,-73.936380,175.000000,5.000000,23.000000,2.010000,2.000000,229.000000
max,3.648561e+07,2.742733e+08,40.913060,-73.717950,10000.000000,1250.000000,607.000000,27.950000,327.000000,365.000000

In [5]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,9138664,Private Lg Room 15 min to Manhattan,47594947,Iris,Queens,Sunnyside,40.74271,-73.92493,Private room,74,2,6,2019-05-26,0.13,1,5
1,31444015,TIME SQUARE CHARMING ONE BED IN HELL'S KITCHEN...,8523790,Johlex,Manhattan,Hell's Kitchen,40.76682,-73.98878,Entire home/apt,170,3,0,NaN,NaN,1,188
2,8741020,Voted #1 Location Quintessential 1BR W Village...,45854238,John,Manhattan,West Village,40.73631,-74.00611,Entire home/apt,245,3,51,2018-09-19,1.12,1,0
3,34602077,Spacious 1 bedroom apartment 15min from Manhattan,261055465,Regan,Queens,Astoria,40.76424,-73.92351,Entire home/apt,125,3,1,2019-05-24,0.65,1,13
4,23203149,Big beautiful bedroom in huge Bushwick apartment,143460,Megan,Brooklyn,Bushwick,40.69839,-73.92044,Private room,65,2,8,2019-06-23,0.52,2,8

3. What do you notice in the data? Look around and see what you can find.

> For example, there are missing values in a few columns and the column `last_review` is a date but it is in string format. Look also at the `price` column, and note the outliers. There are some zeros and some very high prices. After talking to your stakeholders, you decide to consider from a minimum of `$10` to a maximum of `$350` per night.

4. Fix some of the little problems we have found in the data with the following code:

In [6]:
# Drop outliers
min_price = 10
max_price = 350
idx = df['price'].between(min_price, max_price)
df = df[idx].copy()
# Convert last_review to datetime
df['last_review'] = pd.to_datetime(df['last_review'])

Note how we did not impute missing values. We will do that in the inference pipeline, so we will be able to handle missing values also in production.

5. Check with df.info() that all obvious problems have been solved

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19001 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19001 non-null  int64
 1   name                            18994 non-null  object
 2   host_id                         19001 non-null  int64
 3   host_name                       18993 non-null  object
 4   neighbourhood_group             19001 non-null  object
 5   neighbourhood                   19001 non-null  object
 6   latitude                        19001 non-null  float64
 7   longitude                       19001 non-null  float64
 8   room_type                       19001 non-null  object
 9   price                           19001 non-null  int64
 10  minimum_nights                  19001 non-null  int64
 11  number_of_reviews               19001 non-null  int64
 12  last_review                     15243 non-null  datetime64[ns]
 13  reviews_per_month               15243 non-null  float64
 14  calculated_host_listings_count  19001 non-null  int64
 15  availability_365                19001 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(7), object(5)
memory usage: 2.5+ MB

6. Terminate the run by running `run.finish()`

In [8]:
run.finish()

wandb: WARNING Unable to render HTML, can't import display from ipython.core
wandb: WARNING Unable to render HTML, can't import display from ipython.core

7. Save the notebook.